version: '3.8'

services:
  wso2am:
    image: wso2/wso2am:4.4.0
    container_name: wso2am
    depends_on:
      - postgres
    ports:
      - "9444:9444"
      - "9764:9764"
      - "8281:8281"
      - "8244:8244"
    volumes:
      - ./apim-repository/deployment.toml:/home/wso2carbon/wso2am-4.4.0/repository/conf/deployment.toml
      - ./apim-repository/client-truststore.jks:/home/wso2carbon/wso2am-4.4.0/repository/resources/security/client-truststore.jks
      - ./postgresql-42.7.6.jar:/home/wso2carbon/wso2am-4.4.0/repository/components/lib/postgresql-42.7.6.jar

  wso2is:
    image: wso2/wso2is:7.1.0
    container_name: wso2is
    depends_on:
      - postgres
    ports:
      - "9443:9443"
      - "9763:9763"
    volumes:
      - ./is-repository/deployment.toml:/home/wso2carbon/wso2is-7.1.0/repository/conf/deployment.toml
      - ./postgresql-42.7.6.jar:/home/wso2carbon/wso2is-7.1.0/repository/components/lib/postgresql-42.7.6.jar
