version: '3.8'

services:
  wso2am:
    image: wso2am-local:4.4.0
    container_name: wso2am
    ports:
      - "9444:9444"
      - "9764:9764"
      - "8281:8281"
      - "8244:8244"

  wso2is:
    image: wso2is-local:7.1.0
    container_name: wso2is
    ports:
      - "9443:9443"
      - "9763:9763"
